cashier/urls.py
from django.urls import path
from .views import *

app_name    =   'cashier'

urlpatterns = [
    path('', SoldListView.as_view(), name='list'),
    # path('<int:pk>/', SoldDetailView.as_view(), name='Sold_detail'),
    path('new/', SoldCreateView.as_view(), name='Sold_create'),
    # path('<int:pk>/update/', SoldUpdateView.as_view(), name='Sold_update'),
    # path('<int:pk>/delete/', SoldDeleteView.as_view(), name='Sold_delete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('stock/', include('stock.urls')),
    path('', include('cashier.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stock/urls.py
from django.urls import path
from .views import *

app_name    =   'stock'

urlpatterns = [
    path('', StockListView.as_view(), name='list'),
    # path('<int:pk>/', StockDetailView.as_view(), name='Stock_detail'),
    path('new/', StockCreateView.as_view(), name='Stock_create'),
    path('<int:pk>/update/', StockUpdateView.as_view(), name='Stock_update'),
    path('<int:pk>/delete/', StockDeleteView.as_view(), name='Stock_delete'),
    path('<int:box_id>/barcode/', barcode_image, name='box_barcode'),

]

cashier/models.py
from django.db import models
from stock.models import *

class Sold(TimeStampMixin, models.Model):
    box = models.ForeignKey(Box, on_delete=models.CASCADE,verbose_name="التصنيف")

    def __str__(self):
        self.box.name + ' : ' +str(self.box.price)

stock/models.py
from django.db import models
import barcode
from barcode.writer import ImageWriter

class TimeStampMixin(models.Model):
    created_at      = models.DateTimeField(auto_now_add=True,null=True)
    updated_at      = models.DateTimeField(auto_now=True,null=True)
    is_deleted      = models.BooleanField(default=False, null=True)

import random
class Box(models.Model):
    name    = models.CharField(max_length=50, null=True, blank=True, verbose_name="اسم للكرتونة")
    price   = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True,verbose_name="السعر")
    amount  = models.PositiveIntegerField( null=True, blank=True,verbose_name="عدد المنتجات")
    barcode = models.CharField(max_length=100, unique=True, null=True, blank=True, verbose_name="الباركود")

    def __str__(self):
        return self.name + ' : ' + str(self.price) + ' جنيه'
    
    def save(self, *args, **kwargs):
        if not self.barcode:
            self.barcode = self.generate_barcode()
        super().save(*args, **kwargs)

    def generate_barcode(self):
        unique_numbers = random.randint(100000,900000)
        barcode_value = '909102'  # You can customize prefix if needed
        # Generate barcode value here, for example, using the box ID
        # For simplicity, using the box ID as the barcode value
        barcode_value += str(unique_numbers)
        return barcode_value

cashier/forms.py
from django import forms
from .models import Sold

class SoldForm(forms.ModelForm):
    class Meta:
        model = Sold
        fields = ['box']
    
    def clean(self):
        cleaned_data = super().clean()
        # Add custom validation if needed
        return cleaned_data

stock/forms.py
from django import forms
from .models import Box

class BoxForm(forms.ModelForm):
    class Meta:
        model = Box
        fields = ['name', 'price', 'amount']  # Exclude 'barcode' field as it's generated automatically
    
    def clean(self):
        cleaned_data = super().clean()
        # Add custom validation if needed
        return cleaned_data

cashier/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import io
from barcode import EAN13
from barcode.writer import ImageWriter
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages


class SoldListView(ListView):
    model = Sold
    template_name = 'cashier/sold_list.html'
    context_object_name = 'solds'
    ordering = ['-pk']

class SoldCreateView(CreateView):
    model           = Sold
    template_name   = 'cashier/sold_form.html'
    form_class      = SoldForm
    success_url     = reverse_lazy('cashier:list')

stock/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import io
from barcode import EAN13
from barcode.writer import ImageWriter
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages




class StockListView(ListView):
    model = Box
    template_name = 'stock/Stock_list.html'
    context_object_name = 'boxes'
    ordering = ['-pk']

# class StockDetailView(DetailView):
#     model = Box
#     template_name = 'Stock_detail.html'

class StockCreateView(CreateView):
    model           = Box
    template_name   = 'stock/Stock_form.html'
    form_class      = BoxForm
    success_url     = reverse_lazy('stock:list')
    

class StockUpdateView(UpdateView):
    model = Box
    template_name   = 'stock/Stock_form.html'
    form_class      = BoxForm
    success_url     = reverse_lazy('stock:list')


class StockDeleteView(DeleteView):
    model = Box
    template_name = 'stock/stock_confirm_delete.html'
    success_url = reverse_lazy('stock:list')  # Replace with your list view URL

    def delete(self, request, *args, **kwargs):
        """
        Overrides the default delete method to handle deletion and message display.
        """
        self.object.delete()
        messages.success(request, 'Record deleted successfully!')  # Use success message
        return redirect(self.success_url)

def barcode_image(request, box_id):
    Stock = get_object_or_404(Box, pk=box_id)
    if Stock.barcode is not None:
        barcode_value = Stock.barcode
        ean_instance = EAN13(barcode_value, writer=ImageWriter())
        buffer = io.BytesIO()
        ean_instance.write(buffer)
        return HttpResponse(buffer.getvalue(), content_type='image/png')
    else:
        return HttpResponse("No barcode found for this Stock.", status=404)

cashier/templates/cashier/main.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
  <title>صفحة الكاشير</title>
  <link rel="stylesheet" href="{% static 'cashier/css/bootstrap.rtl.min.css' %}">
</head>
<body class="container-fluid">
  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer>
    <p>التصميم والبرمجة بواسطة <a class="" href="#">AMDS</a> الحقوق محفوظة&copy; 2024 </p>
  </footer>

  <script src="{% static 'cashier/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

cashier/templates/cashier/sold_confirm_delete.html
{% extends "cashier/main.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1 class="h1 border p-3 mb-5 mt-3 text-center">هل أنت متأكد من حذف  المنتج  {{box.name}}</h1>
    <div class="row m-5">
        <div class="col-7 m-auto border border-danger p-4">
            <form method="post">
                    {% csrf_token %}
                    {{ form | crispy}}
                <button type="submit" class="btn btn-danger text-white d-block w-100 h3 mt-3">تأكيد الحذف</button>
                <a href="{% url 'stock:list' %}">الغاء</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

cashier/templates/cashier/sold_form.html
{% extends "cashier/main.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1 class="h1 border p-3 mb-5 mt-3 text-center">{% if form.instance.pk %}تعديل{% else %} انشاء {% endif %} سجل منتج  {{cloth.name}}</h1>
    <div class="row m-5">
        <div class="col-7 m-auto border border-danger p-4">
            <form method="post">
                    {% csrf_token %}
                    {{ form | crispy}}
                <button type="submit" class="btn btn-danger text-white d-block w-100 h3 mt-3">تسجيل وحفظ عملية البيع</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

cashier/templates/cashier/sold_list.html
{% extends "cashier/main.html" %}
{% block content %}
<div class="container p-5">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    <h1>قائمة المنتجات</h1>
    <a class="btn btn-primary w-50 m-3" href="{% url 'cashier:Sold_create' %}">اضافة جديد</a>
    <table class="table table-bordered text-center table-striped table-hover">
        <thead>
            <tr class="roww">
                <th class="">الاسم</th>
                <th class="">السعر</th>
                <th class="">تاريخ البيع</th>
                <th>أمر 1</th>
                <th>أمر 2</th>
            </tr>
        </thead>
        <tbody>
        {% for record in solds%}
            <tr class="">
                <td class="">{{record.box.name}}</td>
                <td class="">{{record.box.price}}</td>
                <td>
                <a class="btn btn-info text-white" href="{% url 'stock:box_barcode' record.box.id%}">عرض الباركود للمنتج</a><br>
                </td>
                <td class="">{{record.created_at|date:'Y-m-d / m:s A'}}</td>
                <td><a class="btn btn-danger text-white" href="#">طلب حذف عملية البيع</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

stock/templates/stock/Stock_form.html
{% extends "stock/main.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1 class="h1 border p-3 mb-5 mt-3 text-center">{% if form.instance.pk %}تعديل{% else %} انشاء {% endif %} سجل منتج  {{cloth.name}}</h1>
    <div class="row m-5">
        <div class="col-7 m-auto border border-danger p-4">
            <form method="post">
                    {% csrf_token %}
                    {{ form | crispy}}
                <button type="submit" class="btn btn-danger text-white d-block w-100 h3 mt-3">حفظ</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

stock/templates/stock/Stock_list.html
{% extends "stock/main.html" %}
{% block content %}
<div class="container p-5">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                 <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    <h1>قائمة المنتجات</h1>
    <a class="btn btn-primary w-50 m-3" href="{% url 'stock:Stock_create' %}">اضافة جديد</a>
    <table class="table table-bordered text-center table-striped table-hover">
        <thead>
            <tr class="roww">
                <th class="">الاسم</th>
                <th class="">الكمية</th>
                <th class="">السعر</th>
                <th>أمر 1</th>
                <th>أمر 2</th>
                <th>أمر 3</th>
            </tr>
        </thead>
        <tbody>
        {% for box in boxes%}
            <tr class="">
                <td class="">{{box.name}}</td>
                <td class="">{{box.amount}}</td>
                <td class="">{{box.price}}</td>
                <td>
                <a class="btn btn-info text-white" href="{% url 'stock:box_barcode' box.id%}">عرض الباركود للمنتج</a><br>
                
                </td>
                <td><a class="btn btn-danger text-white" href="{% url 'stock:Stock_update' box.id%}">تعديل البيانات</a></td>
                <td><a class="btn btn-warning text-white" href="{% url 'stock:Stock_delete' box.id%}">حذف المنتج</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

stock/templates/stock/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Django Start</title>
        <style>
            *{text-align: center}
            div{display:flex; justify-content:center}
        </style>
    </head>
    <body>
        <h1 style="text-align: center">Hello, Django-Start</h1>
        <a style="text-align: center" class="github-button" href="https://github.com/islam-kamel/django-start" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-count="true" aria-label="Star islam-kamel/django-start on GitHub">Django-Start</a>
    </body>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</html>

stock/templates/stock/main.html
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
  <title>صفحة المسؤول</title>
  <link rel="stylesheet" href="{% static 'cashier/css/bootstrap.rtl.min.css' %}">
</head>
<body class="container-fluid">
  <main>
    {% block content %}
    {% endblock %}
  </main>

  <footer>
    <p>التصميم والبرمجة بواسطة <a class="" href="#">AMDS</a> الحقوق محفوظة&copy; 2024 </p>
  </footer>

  <script src="{% static 'cashier/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

stock/templates/stock/stock_confirm_delete.html
{% extends "stock/main.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1 class="h1 border p-3 mb-5 mt-3 text-center">هل أنت متأكد من حذف  المنتج  {{box.name}}</h1>
    <div class="row m-5">
        <div class="col-7 m-auto border border-danger p-4">
            <form method="post">
                    {% csrf_token %}
                    {{ form | crispy}}
                <button type="submit" class="btn btn-danger text-white d-block w-100 h3 mt-3">تأكيد الحذف</button>
                <a href="{% url 'stock:list' %}">الغاء</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}